//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EndToEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int Cantidad { get; set; }
        public Nullable<bool> EnDescuento { get; set; }
        public string Descripcion { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<int> Descuento { get; set; }
        public int Precio { get; set; }
    }
}
